apiVersion: apps/v1
kind: Deployment
metadata:
  name: delivery-service
spec:
  selector:
    matchLabels:
      app: delivery-service
  template:
    metadata:
      labels:
        app: delivery-service
    spec:
      nodeSelector:
        role: main
      containers:
        - name: delivery-service
          image: 448049828702.dkr.ecr.ap-northeast-2.amazonaws.com/delivery-service:latest
          imagePullPolicy: Always
          lifecycle:
            preStop:
              exec:
                command: [ "sh", "-c", "sleep 5" ]
          resources:
            requests:
              cpu: "200m"
              memory: "300Mi"
            limits:
              cpu: "400m"
              memory: "512Mi"
          ports:
            - containerPort: 9005
          env:
            - name: SPRING_RABBITMQ_HOST
              value: ${RABBITMQ_IP}
            - name: SPRING_RABBITMQ_PORT
              value: "5672"
            - name: SPRING_R2DBC_URL
              value: r2dbc:mysql://${MYSQL_IP}:3306/delivery
            - name: REDIS_PORT
              value: "6379"
            - name: REDIS_URL
              value: ${REDIS_IP}
            - name: SPRING_PROFILES_ACTIVE
              value: deploy
            - name: SPRING_RABBITMQ_USER
              valueFrom:
                secretKeyRef:
                  name: delivery-service-secrets
                  key: SPRING_RABBITMQ_USER
            - name: SPRING_RABBITMQ_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: delivery-service-secrets
                  key: SPRING_RABBITMQ_PASSWORD
            - name: SPRING_R2DBC_USER
              valueFrom:
                secretKeyRef:
                  name: delivery-service-secrets
                  key: SPRING_R2DBC_USER
            - name: SPRING_R2DBC_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: delivery-service-secrets
                  key: SPRING_R2DBC_PASSWORD
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: delivery-service-secrets
                  key: REDIS_PASSWORD
            - name: REDIS_USER
              valueFrom:
                secretKeyRef:
                  name: delivery-service-secrets
                  key: REDIS_USER

